networks:
  cudo-test-workspace:
    name: cudo-test-workspace
services:
  mysql:
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --general_log"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: cudo
    image: "mysql:5.7.14"
    networks:
    - cudo-test-workspace
    ports:
    - "3306:3306"
    volumes:
    - consistency: delegated
      source: mysql-vol
      target: /var/lib/mysql
      type: volume
    - $PWD/local-dump.sql:/dump.sql
  seed:
    depends_on:
    - mysql
    entrypoint: node data/seed.js
    environment:
      MYSQL_DATABASE: cudo
      MYSQL_HOST: mysql
      MYSQL_PASS: ""
      MYSQL_PORT: "3306"
      MYSQL_USER: root
    image: "node:10.22.0"
    networks:
    - cudo-test-workspace
    volumes:
    - $PWD:/data
    working_dir: /data

version: "3.7"
volumes:
  mysql-vol: ~
